

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-02-12_runs/2015-02-12-mlp-c-01_n60-40-30_e10000_b100_lr0.5_mlp.model.pkl
//


#ifndef MODELM_16d95fdf
#define MODELM_16d95fdf

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 176, 1, Eigen::ColMajor> ModelMInput_16d95fdf;
typedef Eigen::Matrix<float, 2, 1, Eigen::ColMajor> ModelMOutput_16d95fdf;

DMZ_INTERNAL ModelMOutput_16d95fdf applym_16d95fdf(const ModelMInput_16d95fdf& input);


#if TEST_GENERATED_MODELS

bool passm_16d95fdf();

#endif  // TEST_GENERATED_MODELS


#endif  // MODELM_16d95fdf
