

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-02-12_runs/2015-02-12-mlp-a-01_n60-40-30_e10000_b100_lr0.5_mlp.model.pkl
//


#ifndef MODELM_b8c71409
#define MODELM_b8c71409

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 176, 1, Eigen::ColMajor> ModelMInput_b8c71409;
typedef Eigen::Matrix<float, 2, 1, Eigen::ColMajor> ModelMOutput_b8c71409;

DMZ_INTERNAL ModelMOutput_b8c71409 applym_b8c71409(const ModelMInput_b8c71409& input);


#if TEST_GENERATED_MODELS

bool passm_b8c71409();

#endif  // TEST_GENERATED_MODELS


#endif  // MODELM_b8c71409
