

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-02-12_runs/2015-02-12-mlp-b-01_n60-40-30_e10000_b100_lr0.5_mlp.model.pkl
//


#ifndef MODELM_15a2927a
#define MODELM_15a2927a

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 176, 1, Eigen::ColMajor> ModelMInput_15a2927a;
typedef Eigen::Matrix<float, 2, 1, Eigen::ColMajor> ModelMOutput_15a2927a;

DMZ_INTERNAL ModelMOutput_15a2927a applym_15a2927a(const ModelMInput_15a2927a& input);


#if TEST_GENERATED_MODELS

bool passm_15a2927a();

#endif  // TEST_GENERATED_MODELS


#endif  // MODELM_15a2927a
