

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-02-12_runs/2015-02-12-mlp-d-01_n60-40-30_e10000_b100_lr0.5_mlp.model.pkl
//


#ifndef MODELM_47b13bb4
#define MODELM_47b13bb4

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 176, 1, Eigen::ColMajor> ModelMInput_47b13bb4;
typedef Eigen::Matrix<float, 2, 1, Eigen::ColMajor> ModelMOutput_47b13bb4;

DMZ_INTERNAL ModelMOutput_47b13bb4 applym_47b13bb4(const ModelMInput_47b13bb4& input);


#if TEST_GENERATED_MODELS

bool passm_47b13bb4();

#endif  // TEST_GENERATED_MODELS


#endif  // MODELM_47b13bb4
