

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-02-03_runs/2015-02-03-conv01_nk50-40_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b100_lr1.5_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_bf4dd6c8
#define MODELC_bf4dd6c8

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_bf4dd6c8;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_bf4dd6c8;

DMZ_INTERNAL ModelCOutput_bf4dd6c8 applyc_bf4dd6c8(const ModelCInput_bf4dd6c8& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_bf4dd6c8();

#endif  // TEST_GENERATED_MODELS


#endif
