

//
// DO NOT EDIT HERE.
// Autogenerated from 2014-12-18_runs/2014-12-18-conv04_nk30-30_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b50_lr0.05_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_d3fc216e
#define MODELC_d3fc216e

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_d3fc216e;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_d3fc216e;

DMZ_INTERNAL ModelCOutput_d3fc216e applyc_d3fc216e(const ModelCInput_d3fc216e& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_d3fc216e();

#endif  // TEST_GENERATED_MODELS


#endif
