

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-01-15_runs/2015-01-15-mlp01_n176-100-50_e10000_b100_lr0.5_mlp.model.pkl
//


#ifndef MODELM_e43af6f6
#define MODELM_e43af6f6

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 176, 1, Eigen::ColMajor> ModelMInput_e43af6f6;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelMOutput_e43af6f6;

DMZ_INTERNAL ModelMOutput_e43af6f6 applym_e43af6f6(const ModelMInput_e43af6f6& input);


#if TEST_GENERATED_MODELS

bool passm_e43af6f6();

#endif  // TEST_GENERATED_MODELS


#endif  // MODELM_e43af6f6
