

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-01-15_runs/2015-01-15-conv01_nk50-40_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b100_lr1.5_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_5cff994c
#define MODELC_5cff994c

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_5cff994c;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_5cff994c;

DMZ_INTERNAL ModelCOutput_5cff994c applyc_5cff994c(const ModelCInput_5cff994c& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_5cff994c();

#endif  // TEST_GENERATED_MODELS


#endif
