

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2014-12-30_runs/2014-12-30-conv07_nk30-30_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b100_lr0.05_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_918daa9c
#define MODELC_918daa9c

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_918daa9c;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_918daa9c;

DMZ_INTERNAL ModelCOutput_918daa9c applyc_918daa9c(const ModelCInput_918daa9c& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_918daa9c();

#endif  // TEST_GENERATED_MODELS


#endif
