

//
// DO NOT EDIT HERE.
// Autogenerated from 2014-11-17_runs/2014-11-17-conv02_nk30-30_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b50_lr0.05_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_ab0b6054
#define MODELC_ab0b6054

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_ab0b6054;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_ab0b6054;

DMZ_INTERNAL ModelCOutput_ab0b6054 applyc_ab0b6054(const ModelCInput_ab0b6054& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_ab0b6054();

#endif  // TEST_GENERATED_MODELS


#endif
