

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-01-23_runs/2015-01-23-conv01_nk50-40_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b100_lr1.5_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_b14a5bff
#define MODELC_b14a5bff

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_b14a5bff;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_b14a5bff;

DMZ_INTERNAL ModelCOutput_b14a5bff applyc_b14a5bff(const ModelCInput_b14a5bff& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_b14a5bff();

#endif  // TEST_GENERATED_MODELS


#endif
