

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-01-22_runs/2015-01-22-conv01_nk50-40_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b100_lr1.5_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_13a159cd
#define MODELC_13a159cd

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_13a159cd;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_13a159cd;

DMZ_INTERNAL ModelCOutput_13a159cd applyc_13a159cd(const ModelCInput_13a159cd& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_13a159cd();

#endif  // TEST_GENERATED_MODELS


#endif
