

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2014-11-11-conv02_nk50-40_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b50_lr0.05_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_e1533ae9
#define MODELC_e1533ae9

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_e1533ae9;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_e1533ae9;

DMZ_INTERNAL ModelCOutput_e1533ae9 applyc_e1533ae9(const ModelCInput_e1533ae9& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_e1533ae9();

#endif  // TEST_GENERATED_MODELS


#endif
