

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-01-22_runs/2015-01-22-mlp01_n176-100-50_e10000_b100_lr0.5_mlp.model.pkl
//


#ifndef MODELM_95f644e2
#define MODELM_95f644e2

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 176, 1, Eigen::ColMajor> ModelMInput_95f644e2;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelMOutput_95f644e2;

DMZ_INTERNAL ModelMOutput_95f644e2 applym_95f644e2(const ModelMInput_95f644e2& input);


#if TEST_GENERATED_MODELS

bool passm_95f644e2();

#endif  // TEST_GENERATED_MODELS


#endif  // MODELM_95f644e2
