

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-01-15_runs/2015-01-15-mlp01_n400-200-100_e10000_b100_lr1.0_mlp.model.pkl
//


#ifndef MODELM_0ce5632a
#define MODELM_0ce5632a

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 176, 1, Eigen::ColMajor> ModelMInput_0ce5632a;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelMOutput_0ce5632a;

DMZ_INTERNAL ModelMOutput_0ce5632a applym_0ce5632a(const ModelMInput_0ce5632a& input);


#if TEST_GENERATED_MODELS

bool passm_0ce5632a();

#endif  // TEST_GENERATED_MODELS


#endif  // MODELM_0ce5632a
