

//
// DO NOT EDIT HERE.
// Autogenerated from /Users/dgoldman/Projects/clearcut/2015-01-30_runs/2015-01-30-conv01_nk50-40_fs0-5-5_ps0-2-2_h176_bm-full_ib-True_b100_lr1.5_fs1-5-5_ps1-2-3_conv.model.pkl
//


#ifndef MODELC_9ef06a97
#define MODELC_9ef06a97

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 16, 11, Eigen::RowMajor> ModelCInput_9ef06a97;
typedef Eigen::Matrix<float, 10, 1, Eigen::ColMajor> ModelCOutput_9ef06a97;

DMZ_INTERNAL ModelCOutput_9ef06a97 applyc_9ef06a97(const ModelCInput_9ef06a97& input, bool test_generated_models = false);


#if TEST_GENERATED_MODELS

bool passc_9ef06a97();

#endif  // TEST_GENERATED_MODELS


#endif
