

//
// DO NOT EDIT HERE.
// Autogenerated from 2014-11-04_runs/2014-11-04-slash-mlp-02_n80_e1000_b20_lr0.01_mlp.model.pkl
//


#ifndef MODELM_730c4cbd
#define MODELM_730c4cbd

#include "eigen.h"
#include "dmz_macros.h"

typedef Eigen::Matrix<float, 176, 1, Eigen::ColMajor> ModelMInput_730c4cbd;
typedef Eigen::Matrix<float, 2, 1, Eigen::ColMajor> ModelMOutput_730c4cbd;

DMZ_INTERNAL ModelMOutput_730c4cbd applym_730c4cbd(const ModelMInput_730c4cbd& input);


#if TEST_GENERATED_MODELS

bool passm_730c4cbd();

#endif  // TEST_GENERATED_MODELS


#endif  // MODELM_730c4cbd
